import type { SatelliteGroup, GroupInfo } from './constants';

export const GROUP_INFO: Record<SatelliteGroup, GroupInfo> = {
  stations: {
    description: 'Inhabited and autonomous space stations in low Earth orbit, including ISS, CSS (Tiangong), and visiting crew/cargo vehicles.',
    operator: 'NASA, Roscosmos, CNSA, ESA, JAXA',
    orbit: 'LEO (400–420 km)',
    count: '~10',
    since: '1998',
    purpose: 'Crewed Research',
    country: 'International',
    frequency: 'S-band, Ku-band, UHF (145.8/437.8 MHz)',
    minElevationDeg: 5,
  },
  weather: {
    description: 'Meteorological satellites providing global weather imagery, atmospheric sounding, and storm tracking data.',
    operator: 'NOAA, EUMETSAT, CNSA, ISRO, JMA',
    orbit: 'LEO & GEO',
    count: '~50',
    since: '1960s',
    purpose: 'Meteorology',
    country: 'International',
    frequency: 'L-band (1694–1710 MHz), S-band, UHF (137 MHz APT)',
    minElevationDeg: 5,
  },
  noaa: {
    description: 'US polar-orbiting weather satellites transmitting APT/HRPT imagery. Popular targets for amateur radio reception.',
    operator: 'NOAA / NASA',
    orbit: 'Sun-sync LEO (800–870 km)',
    count: '~6',
    since: '1998',
    purpose: 'Weather Imaging',
    country: 'USA',
    frequency: '137 MHz APT, 1698/1707 MHz HRPT',
    minElevationDeg: 5,
  },
  amateur: {
    description: 'Satellites carrying amateur radio transponders, digipeaters, and beacons for ham radio operators worldwide.',
    operator: 'AMSAT, universities, various',
    orbit: 'LEO (400–1500 km)',
    count: '~100+',
    since: '1961',
    purpose: 'Amateur Radio',
    country: 'International',
    frequency: 'VHF/UHF (145/435 MHz), HF (10m/15m)',
    minElevationDeg: 5,
  },
  science: {
    description: 'Scientific research missions studying Earth, space physics, astronomy, and fundamental science from orbit.',
    operator: 'NASA, ESA, JAXA, ISRO, various',
    orbit: 'Various (LEO to L2)',
    count: '~70',
    since: '1960s',
    purpose: 'Scientific Research',
    country: 'International',
    frequency: 'S-band, X-band, Ka-band (varies by mission)',
    minElevationDeg: 5,
  },
  resource: {
    description: 'Earth observation satellites for land/ocean/atmosphere monitoring, agriculture, forestry, and resource management.',
    operator: 'NASA, ESA, CNSA, various',
    orbit: 'Sun-sync LEO (500–900 km)',
    count: '~40',
    since: '1972',
    purpose: 'Earth Observation',
    country: 'International',
    frequency: 'X-band (8 GHz), S-band downlink',
    minElevationDeg: 10,
  },
  goes: {
    description: 'Geostationary Operational Environmental Satellites providing continuous weather imagery of the Western Hemisphere.',
    operator: 'NOAA / NASA',
    orbit: 'GEO (35,786 km)',
    count: '~5',
    since: '1975',
    purpose: 'Weather Monitoring',
    country: 'USA',
    frequency: 'L-band (1686.6 MHz HRIT/LRIT), S-band',
    minElevationDeg: 5,
  },
  'gps-ops': {
    description: 'US Global Positioning System constellation providing precision navigation, timing, and positioning worldwide.',
    operator: 'US Space Force',
    orbit: 'MEO (20,180 km)',
    count: '~31',
    since: '1978',
    purpose: 'Navigation (GNSS)',
    country: 'USA',
    frequency: 'L1 (1575.42 MHz), L2 (1227.6 MHz), L5 (1176.45 MHz)',
    minElevationDeg: 5,
  },
  'glo-ops': {
    description: 'Russian global navigation satellite system, counterpart to GPS. Provides positioning for military and civilian use.',
    operator: 'Roscosmos / Russian MoD',
    orbit: 'MEO (19,130 km)',
    count: '~24',
    since: '1982',
    purpose: 'Navigation (GNSS)',
    country: 'Russia',
    frequency: 'L1 (1602 MHz), L2 (1246 MHz), L3 (1202 MHz)',
    minElevationDeg: 5,
  },
  galileo: {
    description: 'European Union global navigation satellite system providing high-accuracy positioning independent of GPS/GLONASS.',
    operator: 'EU / ESA / EUSPA',
    orbit: 'MEO (23,222 km)',
    count: '~28',
    since: '2011',
    purpose: 'Navigation (GNSS)',
    country: 'EU',
    frequency: 'E1 (1575.42 MHz), E5a/E5b (1176/1207 MHz), E6 (1278 MHz)',
    minElevationDeg: 5,
  },
  beidou: {
    description: 'Chinese global navigation satellite system (BDS) with regional and global coverage for positioning and messaging.',
    operator: 'CNSA / PLA',
    orbit: 'MEO/GEO/IGSO',
    count: '~45',
    since: '2000',
    purpose: 'Navigation (GNSS)',
    country: 'China',
    frequency: 'B1 (1561 MHz), B2 (1207 MHz), B3 (1268 MHz)',
    minElevationDeg: 5,
  },
  sbas: {
    description: 'Satellite-Based Augmentation Systems (WAAS, EGNOS, MSAS, GAGAN) improving GNSS accuracy for aviation.',
    operator: 'FAA, ESA, JAXA, ISRO',
    orbit: 'GEO (35,786 km)',
    count: '~20',
    since: '2003',
    purpose: 'Navigation Augmentation',
    country: 'International',
    frequency: 'L1 (1575.42 MHz), L5 (1176.45 MHz)',
    minElevationDeg: 5,
  },
  iridium: {
    description: 'Global satellite phone and data network. Iridium NEXT constellation replaced original Iridium in 2017–2019.',
    operator: 'Iridium Communications',
    orbit: 'LEO (780 km)',
    count: '~75',
    since: '2017 (NEXT)',
    purpose: 'Communication (Voice/Data)',
    country: 'USA',
    frequency: 'L-band (1616–1626.5 MHz), Ka-band crosslinks',
    minElevationDeg: 8,
  },
  military: {
    description: 'Unclassified military satellites for communications, early warning, surveillance, and signals intelligence.',
    operator: 'US, Russia, China, various',
    orbit: 'Various',
    count: '~100+',
    since: '1960s',
    purpose: 'Defense & Intelligence',
    country: 'International',
    frequency: 'UHF, SHF, EHF (classified/varies)',
    minElevationDeg: 5,
  },
  starlink: {
    description: 'SpaceX mega-constellation for global broadband internet. Largest satellite constellation in history.',
    operator: 'SpaceX',
    orbit: 'LEO (540–570 km)',
    count: '~6400+',
    since: '2019',
    purpose: 'Broadband Internet',
    country: 'USA',
    frequency: 'Ku-band (10.7–12.7 / 14–14.5 GHz), Ka-band, V-band (future)',
    minElevationDeg: 25,
  },
  oneweb: {
    description: 'LEO broadband internet constellation providing global connectivity, including Arctic coverage.',
    operator: 'Eutelsat OneWeb',
    orbit: 'LEO (1,200 km)',
    count: '~630',
    since: '2020',
    purpose: 'Broadband Internet',
    country: 'UK / France',
    frequency: 'Ku-band (10.7–12.75 / 14–14.5 GHz), Ka-band gateway',
    minElevationDeg: 35,
  },
  globalstar: {
    description: 'Satellite phone and IoT data network with spot-beam architecture for voice and low-rate data.',
    operator: 'Globalstar Inc.',
    orbit: 'LEO (1,414 km)',
    count: '~48',
    since: '1998',
    purpose: 'Communication (Voice/IoT)',
    country: 'USA',
    frequency: 'L-band (1610–1618 MHz), S-band (2483–2500 MHz), C-band feeder',
    minElevationDeg: 10,
  },
  orbcomm: {
    description: 'Machine-to-machine (M2M) and IoT messaging constellation for asset tracking, fleet management, and SCADA.',
    operator: 'Orbcomm Inc.',
    orbit: 'LEO (750 km)',
    count: '~36',
    since: '1997',
    purpose: 'IoT / M2M Data',
    country: 'USA',
    frequency: 'VHF (137–138 MHz uplink, 400 MHz downlink)',
    minElevationDeg: 10,
  },
  intelsat: {
    description: 'One of the largest GEO satellite operators providing broadcast TV, telephony, and enterprise data worldwide.',
    operator: 'Intelsat S.A.',
    orbit: 'GEO (35,786 km)',
    count: '~50',
    since: '1965',
    purpose: 'Communication (TV/Data)',
    country: 'USA / Luxembourg',
    frequency: 'C-band (3.4–4.2 / 5.9–6.4 GHz), Ku-band, Ka-band',
    minElevationDeg: 5,
  },
  ses: {
    description: 'Major satellite operator with GEO fleet (SES) and MEO constellation (O3b mPOWER) for video and data.',
    operator: 'SES S.A.',
    orbit: 'GEO + MEO (8,062 km)',
    count: '~70',
    since: '1988',
    purpose: 'Communication (TV/Data)',
    country: 'Luxembourg',
    frequency: 'C-band, Ku-band, Ka-band (O3b mPOWER)',
    minElevationDeg: 5,
  },
  eutelsat: {
    description: 'Major European satellite operator providing TV broadcasting, broadband, and government services via GEO fleet.',
    operator: 'Eutelsat S.A.',
    orbit: 'GEO (35,786 km)',
    count: '~35',
    since: '1983',
    purpose: 'Communication (TV/Data)',
    country: 'France',
    frequency: 'C-band, Ku-band, Ka-band',
    minElevationDeg: 5,
  },
  telesat: {
    description: 'Canadian satellite operator with GEO fleet and planned Lightspeed LEO constellation for global connectivity.',
    operator: 'Telesat Canada',
    orbit: 'GEO + LEO (planned)',
    count: '~15',
    since: '1972',
    purpose: 'Communication (Data)',
    country: 'Canada',
    frequency: 'C-band, Ku-band, Ka-band',
    minElevationDeg: 5,
  },
  kuiper: {
    description: 'Amazon Project Kuiper LEO broadband constellation, competitor to Starlink for global internet access.',
    operator: 'Amazon / Kuiper Systems',
    orbit: 'LEO (590–630 km)',
    count: '~30 (3,236 planned)',
    since: '2024',
    purpose: 'Broadband Internet',
    country: 'USA',
    frequency: 'Ka-band (17.7–20.2 / 27.5–30 GHz)',
    minElevationDeg: 30,
  },
  rassvet: {
    description: 'Russian broadband internet constellation (\u0420\u0430\u0441\u0441\u0432\u0435\u0442) by Bureau 1440 (\u0411\u044e\u0440\u043e 1440) for Russia and global coverage.',
    operator: 'Bureau 1440',
    orbit: 'LEO (~600 km)',
    count: '~15',
    since: '2024',
    purpose: 'Broadband Internet',
    country: 'Russia',
    frequency: 'Ka-band, Ku-band',
    minElevationDeg: 25,
  },
  qianfan: {
    description: 'Chinese mega-constellation (\u5343\u5e06/Qianfan "Thousand Sails") by Shanghai SPACECOM for global broadband internet.',
    operator: 'Shanghai SPACECOM Lab',
    orbit: 'LEO (~1,200 km)',
    count: '~600+ (14,000 planned)',
    since: '2024',
    purpose: 'Broadband Internet',
    country: 'China',
    frequency: 'Ku-band, Ka-band',
    minElevationDeg: 25,
  },
  hulianwang: {
    description: 'Chinese state-backed mega-constellation (\u56fd\u7f51/GuoWang) for broadband internet, China\'s Starlink equivalent.',
    operator: 'China SatNet / SASAC',
    orbit: 'LEO (~1,100 km)',
    count: '~50+ (13,000 planned)',
    since: '2024',
    purpose: 'Broadband Internet',
    country: 'China',
    frequency: 'Ku-band, Ka-band',
    minElevationDeg: 25,
  },
  planet: {
    description: 'Earth imaging constellation of Dove/SuperDove 3U CubeSats capturing daily global imagery at 3\u20135m resolution.',
    operator: 'Planet Labs PBC',
    orbit: 'Sun-sync LEO (475\u2013525 km)',
    count: '~200+',
    since: '2014',
    purpose: 'Earth Imaging',
    country: 'USA',
    frequency: 'X-band (8 GHz downlink), S-band TT&C',
    minElevationDeg: 10,
  },
  spire: {
    description: 'CubeSat constellation for weather data (GNSS-RO), maritime tracking (AIS), and aircraft tracking (ADS-B).',
    operator: 'Spire Global',
    orbit: 'LEO (400\u2013650 km)',
    count: '~100+',
    since: '2015',
    purpose: 'Weather / AIS / ADS-B',
    country: 'USA',
    frequency: 'GNSS-RO L-band, VHF (162 MHz AIS), 1090 MHz ADS-B',
    minElevationDeg: 5,
  },
  radar: {
    description: 'Synthetic Aperture Radar (SAR) satellites for all-weather day/night Earth imaging. Includes ICEYE, Capella, and others.',
    operator: 'ICEYE, Capella Space, Umbra, various',
    orbit: 'Sun-sync LEO (500\u2013600 km)',
    count: '~50+',
    since: '2018',
    purpose: 'SAR Imaging',
    country: 'Finland / USA / International',
    frequency: 'X-band SAR (9.6 GHz), S-band TT&C',
    minElevationDeg: 15,
  },
  cubesat: {
    description: 'CubeSat-class satellites (1U\u201312U) from commercial, university, and government missions worldwide.',
    operator: 'Various',
    orbit: 'LEO (300\u2013700 km)',
    count: '~2,000+',
    since: '2003',
    purpose: 'Various (Tech Demo/Science/Comms)',
    country: 'International',
    frequency: 'VHF/UHF (145/435 MHz), S-band, X-band',
    minElevationDeg: 10,
  },
  geo: {
    description: 'All satellites in geostationary orbit \u2014 stationary above equator. Includes comms, weather, and military.',
    operator: 'Various',
    orbit: 'GEO (35,786 km)',
    count: '~500+',
    since: '1964',
    purpose: 'Mixed (Comms/Weather/Military)',
    country: 'International',
    frequency: 'C/Ku/Ka-band (varies)',
    minElevationDeg: 5,
  },
  'last-30-days': {
    description: 'Satellites launched in the last 30 days. Updated daily to show the most recent additions to orbit.',
    operator: 'Various',
    orbit: 'Various',
    count: '~50\u2013200',
    since: 'N/A (rolling)',
    purpose: 'Recent Launches',
    country: 'International',
    frequency: 'Various',
    minElevationDeg: 5,
  },
  visual: {
    description: 'Brightest satellites visible to the naked eye. Useful for planning visual observation sessions.',
    operator: 'Various',
    orbit: 'Various',
    count: '~100',
    since: 'N/A',
    purpose: 'Visual Observation',
    country: 'International',
    frequency: 'N/A (optical only)',
    minElevationDeg: 5,
  },
  sarsat: {
    description: 'COSPAS-SARSAT search and rescue system. Detects emergency beacons (EPIRB, ELT, PLB) and relays distress alerts.',
    operator: 'NOAA, Roscosmos, EUMETSAT, ISRO',
    orbit: 'LEO + MEO + GEO',
    count: '~10',
    since: '1982',
    purpose: 'Search & Rescue',
    country: 'International',
    frequency: '406 MHz (beacon), 1544 MHz (relay downlink)',
    minElevationDeg: 5,
  },
  education: {
    description: 'CubeSats and small satellites built by universities and student teams for educational and research purposes.',
    operator: 'Universities worldwide',
    orbit: 'LEO (300\u2013700 km)',
    count: '~100+',
    since: '2003',
    purpose: 'Education / STEM',
    country: 'International',
    frequency: 'VHF/UHF (145/435 MHz), S-band (varies)',
    minElevationDeg: 10,
  },
  engineering: {
    description: 'Technology demonstration and experimental satellites testing new hardware, propulsion, and communication systems.',
    operator: 'Various space agencies & companies',
    orbit: 'LEO',
    count: '~50+',
    since: '1990s',
    purpose: 'Technology Demo',
    country: 'International',
    frequency: 'S-band, X-band (varies by mission)',
    minElevationDeg: 10,
  },
  geodetic: {
    description: 'Passive laser retroreflector satellites used for precise geodesy, plate tectonics, and gravity field measurement.',
    operator: 'NASA, ASI, JAXA',
    orbit: 'LEO\u2013MEO (800\u20135,900 km)',
    count: '~10',
    since: '1976',
    purpose: 'Geodesy / Geophysics',
    country: 'USA / Italy / Japan',
    frequency: 'N/A (passive laser retroreflectors)',
    minElevationDeg: 10,
  },
  tdrss: {
    description: 'NASA Tracking and Data Relay Satellite System \u2014 relay network for ISS, Hubble, and LEO spacecraft communications.',
    operator: 'NASA',
    orbit: 'GEO (35,786 km)',
    count: '~9',
    since: '1983',
    purpose: 'Data Relay',
    country: 'USA',
    frequency: 'S-band, Ku-band (13.7 GHz), Ka-band (26 GHz)',
    minElevationDeg: 5,
  },
  molniya: {
    description: 'Russian communications satellites in highly elliptical Molniya orbits optimized for high-latitude coverage.',
    operator: 'Roscosmos / Russian MoD',
    orbit: 'HEO (500\u201340,000 km)',
    count: '~5',
    since: '1965',
    purpose: 'Communication (HEO)',
    country: 'Russia',
    frequency: 'C-band, UHF military bands',
    minElevationDeg: 5,
  },
  argos: {
    description: 'ARGOS Data Collection System satellites relaying environmental data from autonomous platforms worldwide.',
    operator: 'CNES / NOAA / EUMETSAT / ISRO',
    orbit: 'Sun-sync LEO (800\u2013850 km)',
    count: '~10',
    since: '1978',
    purpose: 'Data Collection',
    country: 'France / USA',
    frequency: '401.65 MHz (uplink), 465 MHz (downlink)',
    minElevationDeg: 5,
  },
  dmc: {
    description: 'Disaster Monitoring Constellation providing rapid-revisit Earth imagery for disaster response and management.',
    operator: 'SSTL / DMCii',
    orbit: 'Sun-sync LEO (660\u2013700 km)',
    count: '~8',
    since: '2002',
    purpose: 'Disaster Monitoring',
    country: 'UK / International',
    frequency: 'S-band, X-band',
    minElevationDeg: 10,
  },
  satnogs: {
    description: 'Satellites tracked by the SatNOGS open-source ground station network. Community-curated satellite database.',
    operator: 'Libre Space Foundation',
    orbit: 'LEO',
    count: '~300+',
    since: '2014',
    purpose: 'Open-Source Tracking',
    country: 'International',
    frequency: 'VHF/UHF (various)',
    minElevationDeg: 5,
  },
  'x-comm': {
    description: 'Experimental communication satellites testing new technologies, frequencies, and protocols in orbit.',
    operator: 'Various',
    orbit: 'Various',
    count: '~30',
    since: 'Various',
    purpose: 'Experimental Comms',
    country: 'International',
    frequency: 'Various experimental bands',
    minElevationDeg: 10,
  },
  'other-comm': {
    description: 'Communication satellites not classified in specific operator groups. Regional and niche operators.',
    operator: 'Various regional operators',
    orbit: 'GEO / LEO',
    count: '~200+',
    since: 'Various',
    purpose: 'Communication',
    country: 'International',
    frequency: 'C/Ku/Ka-band (varies)',
    minElevationDeg: 5,
  },
  active: {
    description: 'All cataloged active satellites from the combined CelesTrak database.',
    operator: 'Various',
    orbit: 'Various',
    count: '~10,000+',
    since: 'N/A',
    purpose: 'All Active Payloads',
    country: 'International',
    frequency: 'All bands',
    minElevationDeg: 5,
  },
};
