import type { SatellitePass } from '@/lib/passes';

function icsTimestamp(date: Date): string {
  return date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
}

function escapeText(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');
}

/**
 * Build a calendar event for a satellite pass so the user gets a reminder
 * outside the app. Reminder fires 10 minutes before AOS.
 */
export function buildPassIcs(
  pass: SatellitePass,
  observer: { lat: number; lng: number } | null,
  extraLines: string[] = [],
): string {
  const uid = `pass-${pass.satId}-${pass.startTime.getTime()}@birdwatches.app`;
  const summary = `${pass.satName} pass — ${pass.peakElevation.toFixed(0)}° max`;
  const description = [
    `Satellite: ${pass.satName} (NORAD ${pass.satId})`,
    `Max elevation: ${pass.peakElevation.toFixed(0)}°`,
    `Peak at: ${pass.peakTime.toISOString()}`,
    observer ? `Observer: ${observer.lat.toFixed(4)}, ${observer.lng.toFixed(4)}` : '',
    ...extraLines,
    'Generated by BirdWatches — https://birdwatches.app',
  ]
    .filter(Boolean)
    .join('\n');

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//BirdWatches//Satellite Pass//EN',
    'CALSCALE:GREGORIAN',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${icsTimestamp(new Date())}`,
    `DTSTART:${icsTimestamp(pass.startTime)}`,
    `DTEND:${icsTimestamp(pass.endTime)}`,
    `SUMMARY:${escapeText(summary)}`,
    `DESCRIPTION:${escapeText(description)}`,
    observer ? `GEO:${observer.lat.toFixed(4)};${observer.lng.toFixed(4)}` : '',
    'BEGIN:VALARM',
    'TRIGGER:-PT10M',
    'ACTION:DISPLAY',
    `DESCRIPTION:${escapeText(summary)}`,
    'END:VALARM',
    'END:VEVENT',
    'END:VCALENDAR',
  ]
    .filter(Boolean)
    .join('\r\n');
}

/** Trigger a browser download of an .ics file */
export function downloadIcs(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
